title: "Bukola 'Grace' Omotoso"
email: gracomot@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "/" 
form_url: "https://formspree.io/f/mknkqzwr"
github_username: grace-omotoso
certs: BSc, MsC, CISA, CISM

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg

# your google analytics tag goes here
# how to get your analytics tag?
# https://support.google.com/analytics/answer/1008080
google-analytics: XX-000000000-0
